import { InStockEnum } from '../components/ProductCard/ProductCard.props'

export const cardioEquipments = [
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900',
    oldPrice: '34 900',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900 ₽',
    oldPrice: '34 900 ₽',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
  {
    image: '../public/images/CardioEquipments/CardioEquipmentsB37.png',
    badges: ['new', 'like', 'percentage'],
    icons: true,
    inStock: InStockEnum.inStock,
    title: 'Вертикальный велотренажер B37',
    rating: 5,
    price: 'от 1 134 900 ₽',
    oldPrice: '34 900 ₽',
    characteristics: [
      { title: 'Тип дорожки: ', description: 'Домашняя' },
      { title: 'Бег.полотно: ', description: '1200 х 450 мм' },
      { title: 'Мощность двигателя: ', description: '2,0 л.с.' },
      { title: 'Беговое полотно: ', description: '2-х слойное' },
      { title: 'Производитель : ', description: 'Cardio Power' },
    ],
    button: true,
  },
]
