export const forHomeCatalog = [
  {
    image: '/images/forHome/one.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/two.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/three.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/four.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/one.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/two.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/three.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
  {
    image: '/images/forHome/four.png',
    title: 'Кардиотренажеры',
    list: [
      { title: 'Беговые дорожки', quantity: 57 },
      { title: 'Эллиптические тренажеры', quantity: 27 },
      { title: 'Велотренажеры', quantity: 19 },
      { title: 'Cтепперы ', quantity: 17 },
      { title: 'Гребные тренажеры', quantity: 5 },
      { title: 'Сайклинг', quantity: 20 },
      { title: 'Горнолыжные тренажеры', quantity: 14 },
    ],
  },
]
